# Generated by Django 4.0.3 on 2022-03-27 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
